language: python

cache: pip

git:
  depth: 5
  quiet: true
  submodules: false

install:
  - pip install -r requirements.txt
  - pip install psycopg2-binary mysql-connector-python

script:
  - coverage erase
  - coverage run manage.py test

after_success:
  - codecov

services:
  - postgresql
  - mysql

matrix:
  include:
    - python: 3.6
      dist: xenial
      name: Python 3.6 on Ubuntu Xenial with SQLite
      env:
        - JOKES_API_DATABASE_URL=sqlite://

    - python: 3.6
      dist: xenial
      name: Python 3.6 on Ubuntu Xenial with PostgreSQL
      env:
        - JOKES_API_DATABASE_URL=postgres://postgres@localhost:5432/postgres

    - python: 3.6
      dist: xenial
      name: Python 3.6 on Ubuntu Xenial with MySQL
      env:
        - JOKES_API_DATABASE_URL=mysql+mysqlconnector://travis@localhost:3306/travis

    - python: 3.7
      dist: bionic
      name: Python 3.7 on Ubuntu Bionic with SQLite
      env:
        - JOKES_API_DATABASE_URL=sqlite://

    - python: 3.7
      dist: xenial  # postgres on bionic is not working
      name: Python 3.7 on Ubuntu Xenial with PostgreSQL
      env:
        - JOKES_API_DATABASE_URL=postgres://postgres@localhost:5432/postgres

    - python: 3.7
      dist: bionic
      name: Python 3.7 on Ubuntu Bionic with MySQL
      env:
        - JOKES_API_DATABASE_URL=mysql+mysqlconnector://travis@localhost:3306/travis
